---
- name: Part of the trusted set of servers

  block:


    - name: add firewalld rule for trusted network
      firewalld:
        source: "{{ hostvars[item]['ansible_host'] }}"
        permanent: true
        state: enabled
#      immediate: yes
        zone: trusted
      when: hostvars[item]['trusted_host'] is defined and hostvars[item]['trusted_host'] == 'yes'
      loop: "{{ groups['all'] }}"



