---
- name: Install and cofigure ehos-head node

  block:

    - name: Create ehos group
      user:
        name: "{{ehos_user}}"

    - name: Create ehos user
      user:
        name: "{{ehos_user}}"
        group: "{{ehos_user}}"
        groups: adm

    - name: check if ssh-key exists
      become: true
      become_user: "{{ehos_user}}"
      stat:
        path: $HOME/.ssh/id_rsa
      register: result

    - name: create ssh key for connecting to nodes
      become: true
      become_user: "{{ehos_user}}"
      command: ssh-keygen -t rsa -f $HOME/.ssh/id_rsa -q -P ""
      when: result.stat.exists == false

    - name: change group owner of /usr/local
      file:
        dest: /usr/local/
        group: adm
        recurse: yes

    - name: install EHOS
#      command: pip3 install --prefix=/usr/local/ https://github.com/elixir-no-nels/ehos-python/archive/v1.1.0.tar.gz
      command: pip3 install --prefix=/usr/local/ git+https://github.com/elixir-no-nels/ehos-python.git

    - name: setup log dir for EHOS
      file:
        path: /var/log/ehos
        state: directory
        owner: "{{ehos_user}}"
        group: "{{ehos_user}}"
        mode: 0775

    - name: Deploy ehosd config file
      template:
        src: templates/ehos/ehos.yaml.j2
        dest: /usr/local/etc/ehos.yaml
        owner: "{{ehos_user}}"
        group: "{{ehos_user}}"

    - name: Deploy ehos execute image config file
      template:
        src: templates/ehos/execute.yaml.j2
        dest: /usr/local/etc/ehos_execute.yaml
        owner: "{{ehos_user}}"
        group: "{{ehos_user}}"

    - name: Deploy ehos systemd file
      template:
        src: templates/ehos/ehos.service.j2
        dest: /etc/systemd/system/ehos.service
#        daemon_reload: yes

    - name: htcondor gpg-key
      rpm_key:
        key: "https://research.cs.wisc.edu/htcondor/yum/RPM-GPG-KEY-HTCondor"
        state: present

    - name: Add htcondor repo
      yum_repository:
        name: "htcondor"
        description: "HTCondor RPM Repository"
        file: "htcondor"
        baseurl: "https://research.cs.wisc.edu/htcondor/yum/stable/8.8/rhel{{ansible_distribution_major_version}}"
        enabled: yes
        priority: "1"

    - name: install condor
      yum: name=condor

    - name: Copy htcondor personal-config
      template:
        src: templates/ehos/condor_master.j2
        dest: /etc/condor/config.d/99ehos.config
      register: condor_config

    - name: restart htcondor
      service: name=condor state=restarted
      when: condor_config.changed

    - name: Make sure condor is running
      systemd:
        state: started
        name: condor

    - name: set condor password
      command: "{{item}}"
      with_items:
        - sleep 5
        - /usr/sbin/condor_store_cred -p {{condor_password}} -f /var/lock/condor/pool_password
        - /usr/sbin/condor_reconfig

    - name: ehos config file status
      stat:
        path: /usr/local/etc/ehos.yaml
      register: ehos_config

    - name: create cloud image and configure cloud settings
      command: /usr/local/bin/ehos_cloud_setup.py --ssh-key ~{{ehos_user}}/.ssh/id_rsa.pub --create-images -B /usr/local/etc/ehos_execute.yaml /usr/local/etc/ehos.yaml
      when: ehos_config.changed

    - name: Make sure ehos is running
      systemd:
        state: started
        enabled: yes
        name: ehos
