certbot_auto_renew: true
certbot_auto_renew_user: "root"
certbot_auto_renew_hour: "3"
certbot_auto_renew_minute: "30"
certbot_auto_renew_options: "--quiet --no-self-upgrade"

certbot_admin_email: "{{galaxy_admin}}"
certbot_create_if_missing: true
certbot_create_standalone_stop_services: []
certbot_create_method: standalone

certbot_certs:
    - domains:
      - "{{galaxy_host}}"
