id: nels_import_history
type:
  - history-menu
activate: false
title: Import History

function: >
  action="import";
  galaxy_url=window.location.protocol+"//"+window.location.host + Galaxy.root +"nga/history/import/request/";
  console.log(galaxy_url);
  window.location.href = galaxy_url

