certbot_auto_renew: true
certbot_auto_renew_user: "root"
certbot_auto_renew_hour: "{{ 23 |random(seed=inventory_hostname)  }}"
certbot_auto_renew_minute: "{{ 59 |random(seed=inventory_hostname)  }}"
certbot_auto_renew_options: "--quiet --no-self-upgrade"

certbot_admin_email: "{{galaxy_admin_email}}"
certbot_create_if_missing: true
certbot_create_standalone_stop_services: []
certbot_create_method: standalone

certbot_certs:
    - domains:
      - "{{inventory_hostname}}"
