- src: galaxyproject.galaxy
  version: 0.8.4
- src: galaxyproject.nginx
  version: 0.6.0
- src: galaxyproject.postgresql
  version: 1.0.1
- src: natefoo.postgresql_objects
  version: 1.1
- src: geerlingguy.pip
  version: 1.0.0
- src: uchida.miniconda
  version: 0.3.0
- src: https://github.com/usegalaxy-eu/ansible-role-supervisor
  name: usegalaxy-eu.supervisor
- src: https://github.com/usegalaxy-eu/ansible-certbot
  name: usegalaxy-eu.certbot
- src: https://github.com/galaxyproject/ansible-galaxy-tools.git
  name: usegalaxy.galaxy-tools
- src: https://github.com/galaxyproject/ansible-galaxy-extras.git
  name: usegalaxy.galaxy-extras
- src: https://github.com/rossmcdonald/telegraf
  name: rossmcdonald.telegraf
