# This is just a sample file. For a fully documented version of this file, see
# https://github.com/galaxyproject/ansible-galaxy-tools/blob/master/files/tool_list.yaml.sample
tools:
  - name: 'fastqc'
    owner: 'devteam'
    tool_panel_section_id: 'QC'
  - name: 'bwa'
    owner: 'devteam'
    tool_panel_section_id: 'NGS'
